#!/usr/bin/env python3
"""
build_deploy_zip.py: pack the app for a manual cPanel upload.

WHY THIS EXISTS: pushing to GitHub does not deploy anything. cPanel Git Version Control
runs .cpanel.yml when you push to the repository HOSTED ON CPANEL, and this project's
origin is GitHub, so nothing on the server ever hears about a push. Uploading this zip
is the way in.

Verified 2026-08-09: main was pushed to GitHub with a full release on it, and five
minutes of polling https://stemjobs1.astrochakra.co showed the served style.css version
unchanged, the old login copy still in place, and no reference to the new tip.js. The
git path had not run at all.

An earlier version of this note blamed .cpanel.yml's DEPLOYPATH, which used to point at
/home/bnrqpozr/Stemjobs, the account suspended around 2026-07-21. That was true once and
is not the reason any more: DEPLOYPATH was since changed to $HOME/stemjobs, which
resolves to whichever account owns the repo. The path is fine. Nothing invokes it.

Two ways to make git deploys actually work, if that is ever worth doing:
  * add the cPanel repository as a second remote and push to both, or
  * point a GitHub webhook at cPanel so it pulls and runs the deploy task.
Neither is set up today, so treat the zip as the deploy mechanism rather than a fallback.

This packs EXACTLY the same file list .cpanel.yml deploys, so the two stay in step and
switching to a working git deploy later changes nothing. That list now includes
static/dist, the committed React bundle, which arrives for free because "static" is in
DIRS and the walk is recursive.

    python scripts/build_deploy_zip.py            -> ../stemjobs1_deploy.zip
    python scripts/build_deploy_zip.py out.zip

The archive is FLAT: its entries sit at the root, so extracting it inside the app
directory on the server lands every file exactly where Passenger expects it.

NOT included, deliberately:
  .env / secrets            never leave this machine
  jdmeta.json               30+ MB, and there is nowhere fresh to copy it FROM: it is built
                            on the GitHub Actions runner (.github/workflows/scrape.yml at the
                            repo root), whose filesystem is discarded when the run ends. An
                            earlier version of this note claimed it was "regenerated by the
                            scraper on its own host", which was never true and quietly cost
                            the live site every JD-derived filter. Everything the feed FILTERS
                            on now lives in real jobs columns instead (exp_max_years,
                            sponsor_jd, sponsor_reason, loc_*, salary_*), which reach the
                            server through Supabase with no file deploy — run
                            db.JOBS_DERIVED_SQL once in the SQL Editor to create them. What
                            is still lost by not shipping this file is meta["analyzed"], so
                            live per-user scoring falls back to the stored match_score.
  scripts/                  verification tools, not runtime
  __pycache__, *.pyc        stale bytecode breaks more deploys than it fixes
"""
import os
import re
import sys
import json
import time
import hashlib
import zipfile

# Mirrors the /bin/cp list in .cpanel.yml. Keep the two in sync — the check below fails the
# build if they drift, because a bundle missing a module web.py imports is a dead site.
FILES = [
    "web.py", "core.py", "job_categories.py", "db.py", "auth.py", "analytics.py", "jdrender.py",
    "passenger_wsgi.py",
    # The two storage transports. db.py imports pgrest when PG_DSN is set and web.py
    # imports dbproxy unconditionally, so a bundle without them is a site that ImportErrors
    # on the first request. The check below caught exactly that and refused to build.
    "pgrest.py", "dbproxy.py",
    # read-only cPanel UAPI client; web.py imports it for the admin panel's host figures
    "cpanelapi.py",
    # the offline résumé rubric behind /resume; imports resume_brain, already in DIRS
    "resume_score.py",
    # the Skills category. Imported by resume_score, NOT by web.py, so the import guard below
    # cannot infer it -- it has to be named here or the bundle ships a dormant check.
    "resume_keywords.py",
    # per-bullet review (the Bullets tab). Imported by web.py, so the guard below would catch
    # a missing entry -- listed here anyway so the two deploy routes stay identical.
    "resume_bullets.py",
    # The role/employer norms READER. web.py imports it unconditionally, so a bundle
    # without it is a site that ImportErrors on the first request -- required, not
    # optional. The 640 KB table it reads is the optional half, below.
    "norms.py",
    "requirements-cpanel.txt", "idf.json", "sponsors.txt",
    # careers_us.md is NOT here any more. /careers is a 301 to /companies and nothing
    # reads the file at runtime; it is now a build input to scripts/build_companies.py,
    # which bakes its careers links into companies.json.
    # The /companies directory, built by scripts/build_companies.py. REQUIRED rather than
    # optional: the other data files each dim one badge when absent, but without this one
    # /companies has nothing at all to render, so a bundle missing it should not build.
    "companies.json",
    # The cPanel cron entry point. It shipped by NEITHER route until 2026-08-25 -- hand-placed
    # once and 8 commits stale by the time anyone looked. Named rather than sweeping bin/ into
    # DIRS, because that directory also holds a gitignored 50 MB tectonic.exe that DIRS (which
    # walks the filesystem, not git) would cheerfully bundle.
    "bin/cron_scrape.sh",
    "scripts/backfill_job_categories.py", "scripts/repair_clipped_jds.py",
    "MIGRATION_job_categories.sql", "MIGRATION_jd_full_text.sql",
]
# Present-if-built data files. Each feature stays dormant without its file, which is the
# contract core.load_sponsor_counts / load_everify already have — so a missing one is fine.
#
# resume.txt is NOT optional in the same sense, and it is here because leaving it out broke
# something silently. score_jobs aborts with "No resume.txt found — scores would all be 0" and
# EXITS 0, so a scheduled run scrapes, logs a success, and never scores a thing. That was
# invisible while scoring only ran on GitHub Actions, which gets the file from the repo
# checkout; the moment a cPanel cron started scoring, the deploy bundle became the thing that
# had to carry it. Listed as optional rather than required only so a build without it still
# produces a bundle — the site runs fine, it just cannot score.
OPTIONAL_FILES = ["sponsor_counts.json", "sponsor_years.json", "everify.txt", "visa_tags.json",
                  "resume.txt",
                  # company -> domain, built by scripts/build_logos.py --write-domains. The
                  # app degrades to guessing a domain from the company name without it, which is
                  # what shipped before and is wrong for 22% of companies. Optional in the same
                  # sense as the rest: absent file, old behaviour, no crash.
                  "company_domains.json",
                  # Built by scripts/build_resume_vocab.py. Absent -> the spelling check and
                  # the per-track keyword expectations go dormant (excluded from the score,
                  # not awarded full marks), which is the same contract as everything above.
                  "resume_vocab.json", "resume_keywords.json",
                  # Built by scripts/build_norms.py: what each role usually asks for and
                  # which tools each employer leans on. Absent -> norms.load_norms()
                  # returns {} and the /job panel is simply not rendered, which is the
                  # same contract as everything above.
                  "norms.json"]
DIRS = ["scraper", "resume_brain", "templates", "static"]
SKIP_DIRS = {"__pycache__", ".pytest_cache"}
SKIP_EXT = {".pyc", ".pyo"}

# ----------------------------- the drift manifest -----------------------------
# A deploy here is a zip extracted over the top of a running app, so it OVERWRITES silently: no
# diff, no conflict, no warning. That is fine while the server only ever runs what this script
# shipped -- and on 2026-08-24 an audit found it does not. Production was serving a
# templates/profile.html carrying an "Appearance" card (#themepick, window.__themeSet) that has
# never existed in any commit, a base.html MISSING the theme toggle added in 5bb4dc7 two months
# earlier, and a welcome.html rendering one callout twice. Hand-edited in cPanel's File Manager --
# the same File Manager the documented deploy procedure uses -- and the next build of this zip
# would have destroyed all of it without printing a line.
#
# So the bundle now carries a hash of every file it ships from the two directories a File Manager
# edit can reach. web.py::template_drift() compares what is running against it and says so on
# /admin. It cannot PREVENT a hand edit; it makes one impossible to miss before the deploy that
# erases it.
MANIFEST = "deploy_manifest.json"
# Not all of DIRS: scraper/ and resume_brain/ are only ever touched by a deploy, so hashing them
# would make every scraper release print a drift report about itself.
MANIFEST_DIRS = ("templates", "static")


def file_sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def manifest_for(dirs=MANIFEST_DIRS):
    """{posix path: sha256} over the shipped files in `dirs`. web.py reimplements these few
    lines rather than import them, because scripts/ is not in the deploy bundle."""
    out = {}
    for d in dirs:
        if not os.path.isdir(d):
            continue
        for root, dirnames, filenames in os.walk(d):
            dirnames[:] = [x for x in dirnames if x not in SKIP_DIRS]
            for name in sorted(filenames):
                if os.path.splitext(name)[1] in SKIP_EXT:
                    continue
                rel = os.path.join(root, name).replace(os.sep, "/")
                out[rel] = file_sha256(rel)
    return out


def main():
    app = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    os.chdir(app)
    out = sys.argv[1] if len(sys.argv) > 1 else os.path.join("..", "stemjobs1_deploy.zip")

    missing = [f for f in FILES if not os.path.isfile(f)]
    if missing:
        sys.exit("  Refusing to build an incomplete bundle — missing: %s" % ", ".join(missing))

    # THE CHECK THE DOCSTRING ABOVE HAS ALWAYS PROMISED, now actually performed. It used to
    # verify only that the listed files EXIST, which cannot catch the failure that matters: a
    # module web.py imports and this list forgot. That ships a bundle whose first request is an
    # ImportError, i.e. a dead site, and it happened for real — jdrender.py was added to web.py
    # on 2026-08-12 and this list did not know about it.
    #
    # Reads web.py's own top-level imports and requires every one that resolves to a .py file in
    # the app directory to be in FILES. Text-scanned rather than imported, because importing
    # web.py here would need Flask, the .env and a live Supabase.
    src = open("web.py", encoding="utf-8").read()
    imported = set(re.findall(r"^\s*import\s+([a-zA-Z_][\w]*)", src, re.M))
    imported |= set(re.findall(r"^\s*from\s+([a-zA-Z_][\w]*)\s+import", src, re.M))
    local = {m for m in imported if os.path.isfile(m + ".py")}
    packaged = {f[:-3] for f in FILES if f.endswith(".py")} | set(DIRS)
    forgotten = sorted(local - packaged)
    if forgotten:
        sys.exit("  Refusing to build: web.py imports %s, which this bundle would not ship.\n"
                 "  Add %s to FILES here AND to the /bin/cp line in ../.cpanel.yml — the two\n"
                 "  lists deploy the same app by two different routes and must not drift."
                 % (", ".join(forgotten), ", ".join(f + ".py" for f in forgotten)))

    # And the other direction: FILES must not promise something .cpanel.yml would leave behind.
    #
    # This used to check only `f.endswith(".py")`, which made the check blind to exactly the
    # entries most likely to be forgotten — data files, added one at a time as features land.
    # It found resume.txt missing from .cpanel.yml the moment the filter came off, a real gap
    # that had been silent since the file was added to OPTIONAL_FILES.
    try:
        cp = open(os.path.join("..", ".cpanel.yml"), encoding="utf-8").read()
        absent = sorted(f for f in FILES if ('"$SRC/%s"' % f) not in cp)
        if absent:
            print("  WARNING: in FILES but not in .cpanel.yml's cp line: %s" % ", ".join(absent))
            print("           the zip will be complete; a git-based deploy would not be.")
        # OPTIONAL_FILES travels by the `for f in ...` loop rather than the cp line, so it is
        # matched as a bare word.
        opt_absent = sorted(f for f in OPTIONAL_FILES if f not in cp)
        if opt_absent:
            print("  WARNING: in OPTIONAL_FILES but not in .cpanel.yml: %s"
                  % ", ".join(opt_absent))
    except OSError:
        pass

    def _ship(z, path, arc=None):
        """z.write, plus the executable bit for shell scripts.

        zipfile takes the mode from os.stat, and on Windows that is 0o666 with no exec bit at
        all -- so a .sh unzipped on the server lands non-executable. The crontab invokes
        cron_scrape.sh DIRECTLY, so that is not cosmetic: it is `Permission denied` at 13:00
        with only a MAILTO to say so. Set on the central directory, which is what unzip reads.
        """
        arc = arc or path
        z.write(path, arc)
        if arc.endswith(".sh"):
            zi = z.getinfo(arc)
            # BOTH LINES, and the first is the one that is easy to miss. Info-ZIP reads the
            # Unix mode out of external_attr ONLY when "version made by" says Unix; zipfile
            # sets that from the HOST it runs on, which here is Windows (create_system 0,
            # FAT). Setting the mode alone produced an archive listing as `-rw---- fat` that
            # unzip extracted 0o644 -- verified against the real server, where it silently
            # undid this whole fix. 3 = Unix.
            zi.create_system = 3
            zi.external_attr = 0o100755 << 16

    added, skipped = [], []
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as z:
        for f in FILES:
            _ship(z, f)
            added.append(f)
        for f in OPTIONAL_FILES:
            if os.path.isfile(f):
                _ship(z, f)
                added.append(f)
            else:
                skipped.append(f)
        for d in DIRS:
            if not os.path.isdir(d):
                skipped.append(d + "/")
                continue
            for root, dirnames, filenames in os.walk(d):
                dirnames[:] = [x for x in dirnames if x not in SKIP_DIRS]
                for name in sorted(filenames):
                    if os.path.splitext(name)[1] in SKIP_EXT:
                        continue
                    p = os.path.join(root, name)
                    _ship(z, p, p.replace(os.sep, "/"))
                    added.append(p)
        # Last, so it describes the bytes actually written above.
        z.writestr(MANIFEST, json.dumps(
            {"built_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
             "dirs": list(MANIFEST_DIRS), "files": manifest_for()},
            indent=1, sort_keys=True))
        added.append(MANIFEST)

    size = os.path.getsize(out)
    print("Wrote %s  (%d files, %.1f MB)" % (os.path.abspath(out), len(added), size / 1e6))
    if skipped:
        print("Not present, so not included: %s" % ", ".join(skipped))
    print("\nUpload it in cPanel -> File Manager -> the app's directory -> Upload,")
    print("then Extract, then touch tmp/restart.txt so Passenger reloads.")
    print("")
    print("BEFORE YOU EXTRACT: this zip OVERWRITES templates/ and static/ wholesale. If the")
    print("server has been hand-edited that edit is gone, and no copy of it exists anywhere.")
    print("/admin reports the drift the LAST bundle's %s recorded -- read it first." % MANIFEST)
    # This bundle is CODE ONLY. Every document reader is imported lazily, so a host missing one
    # boots fine and just loses the feature -- which is how a live server ended up answering
    # "This server can't read .pdf files yet" with pypdf sitting unread in requirements.
    print("\nIf requirements-cpanel.txt changed, also: Setup Python App -> Run Pip Install.")
    print("What the host actually has: /brain/pdf_diag -> upload_readers.")


if __name__ == "__main__":
    main()
