#!/usr/bin/env python3
"""
build_deploy_zip.py: pack the app for a manual cPanel upload.

WHY THIS EXISTS: pushing to GitHub does not deploy anything. cPanel Git Version Control
runs .cpanel.yml when you push to the repository HOSTED ON CPANEL, and this project's
origin is GitHub, so nothing on the server ever hears about a push. Uploading this zip
is the way in.

Verified 2026-08-09: main was pushed to GitHub with a full release on it, and five
minutes of polling https://stemjobs1.astrochakra.co showed the served style.css version
unchanged, the old login copy still in place, and no reference to the new tip.js. The
git path had not run at all.

An earlier version of this note blamed .cpanel.yml's DEPLOYPATH, which used to point at
/home/bnrqpozr/Stemjobs, the account suspended around 2026-07-21. That was true once and
is not the reason any more: DEPLOYPATH was since changed to $HOME/stemjobs, which
resolves to whichever account owns the repo. The path is fine. Nothing invokes it.

Two ways to make git deploys actually work, if that is ever worth doing:
  * add the cPanel repository as a second remote and push to both, or
  * point a GitHub webhook at cPanel so it pulls and runs the deploy task.
Neither is set up today, so treat the zip as the deploy mechanism rather than a fallback.

This packs EXACTLY the same file list .cpanel.yml deploys, so the two stay in step and
switching to a working git deploy later changes nothing. That list now includes
static/dist, the committed React bundle, which arrives for free because "static" is in
DIRS and the walk is recursive.

    python scripts/build_deploy_zip.py            -> ../stemjobs1_deploy.zip
    python scripts/build_deploy_zip.py out.zip

The archive is FLAT: its entries sit at the root, so extracting it inside the app
directory on the server lands every file exactly where Passenger expects it.

NOT included, deliberately:
  .env / secrets            never leave this machine
  jdmeta.json               30+ MB, and there is nowhere fresh to copy it FROM: it is built
                            on the GitHub Actions runner (.github/workflows/scrape.yml at the
                            repo root), whose filesystem is discarded when the run ends. An
                            earlier version of this note claimed it was "regenerated by the
                            scraper on its own host", which was never true and quietly cost
                            the live site every JD-derived filter. Everything the feed FILTERS
                            on now lives in real jobs columns instead (exp_max_years,
                            sponsor_jd, sponsor_reason, loc_*, salary_*), which reach the
                            server through Supabase with no file deploy — run
                            db.JOBS_DERIVED_SQL once in the SQL Editor to create them. What
                            is still lost by not shipping this file is meta["analyzed"], so
                            live per-user scoring falls back to the stored match_score.
  scripts/                  verification tools, not runtime
  __pycache__, *.pyc        stale bytecode breaks more deploys than it fixes
"""
import os
import sys
import zipfile

# Mirrors the /bin/cp list in .cpanel.yml. Keep the two in sync — the check below fails the
# build if they drift, because a bundle missing a module web.py imports is a dead site.
FILES = [
    "web.py", "core.py", "db.py", "auth.py", "analytics.py", "passenger_wsgi.py",
    "requirements-cpanel.txt", "idf.json", "careers_us.md", "sponsors.txt",
]
# Present-if-built data files. Each feature stays dormant without its file, which is the
# contract core.load_sponsor_counts / load_everify already have — so a missing one is fine.
OPTIONAL_FILES = ["sponsor_counts.json", "sponsor_years.json", "everify.txt", "visa_tags.json"]
DIRS = ["scraper", "resume_brain", "templates", "static"]
SKIP_DIRS = {"__pycache__", ".pytest_cache"}
SKIP_EXT = {".pyc", ".pyo"}


def main():
    app = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    os.chdir(app)
    out = sys.argv[1] if len(sys.argv) > 1 else os.path.join("..", "stemjobs1_deploy.zip")

    missing = [f for f in FILES if not os.path.isfile(f)]
    if missing:
        sys.exit("  Refusing to build an incomplete bundle — missing: %s" % ", ".join(missing))

    added, skipped = [], []
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as z:
        for f in FILES:
            z.write(f, f)
            added.append(f)
        for f in OPTIONAL_FILES:
            if os.path.isfile(f):
                z.write(f, f)
                added.append(f)
            else:
                skipped.append(f)
        for d in DIRS:
            if not os.path.isdir(d):
                skipped.append(d + "/")
                continue
            for root, dirnames, filenames in os.walk(d):
                dirnames[:] = [x for x in dirnames if x not in SKIP_DIRS]
                for name in sorted(filenames):
                    if os.path.splitext(name)[1] in SKIP_EXT:
                        continue
                    p = os.path.join(root, name)
                    z.write(p, p.replace(os.sep, "/"))
                    added.append(p)

    size = os.path.getsize(out)
    print("Wrote %s  (%d files, %.1f MB)" % (os.path.abspath(out), len(added), size / 1e6))
    if skipped:
        print("Not present, so not included: %s" % ", ".join(skipped))
    print("\nUpload it in cPanel -> File Manager -> the app's directory -> Upload,")
    print("then Extract, then touch tmp/restart.txt so Passenger reloads.")


if __name__ == "__main__":
    main()
