#!/usr/bin/env python3
"""Write schema.sql for the `public` schema, by asking Postgres to describe itself.

WHY NOT pg_dump. It is the right tool and this is not a replacement for it in general. It is a
replacement here because pg_dump is a binary that has to be installed, and on a managed Windows
machine without winget or admin rights that is a wall. psycopg2 installs from pip and is needed
by pgrest.py anyway, so this route has no prerequisite the project doesn't already have.

WHY IT IS NOT GUESSWORK, which was the objection to hand-writing DDL. Every definition below
comes out of Postgres's own catalog formatters -- pg_get_constraintdef, pg_get_indexdef,
pg_get_triggerdef, pg_get_functiondef, pg_get_expr, format_type. The server prints its own
constraints, indexes, triggers, functions and column defaults; this only orders them and wraps
them in CREATE TABLE. That matters most for the one that would otherwise be silently wrong:
jobs.first_seen is owned by a column DEFAULT plus a trigger, and both come through verbatim.

WHAT IS DELIBERATELY OMITTED, and why none of it applies to the destination:
  * owners and grants   -- the cPanel app connects as the database owner; Supabase's role names
                           (anon, authenticated, service_role) do not exist there and a GRANT
                           naming them would abort the load.
  * RLS policies        -- same reason: they are written against those roles. The app has always
                           talked to this database as a privileged role, never as `anon`.
  * extensions          -- listed as comments at the top rather than emitted, because a shared
                           host usually forbids CREATE EXTENSION and a hard failure on line 1
                           is a worse outcome than a note saying which ones were present.

    python scripts/dump_schema.py                 # -> schema.sql
    python scripts/dump_schema.py --out other.sql
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.stdout.reconfigure(encoding="utf-8", errors="replace")

DSN_FILE = ".supabase_dsn"


def dsn():
    try:
        s = open(DSN_FILE, encoding="utf-8").read().strip()
    except Exception:
        sys.exit("No %s — put the Supabase session-pooler URL there first." % DSN_FILE)
    if not s:
        sys.exit("%s is empty." % DSN_FILE)
    return s


def q(cur, sql, args=None):
    cur.execute(sql, args or ())
    return cur.fetchall()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="schema.sql")
    ap.add_argument("--schema", default="public")
    a = ap.parse_args()

    import psycopg2
    conn = psycopg2.connect(dsn(), connect_timeout=25)
    cur = conn.cursor()
    S = a.schema
    out = ["-- Generated by scripts/dump_schema.py from the live database.",
           "-- Owners, grants, RLS policies and extensions are intentionally not included;",
           "-- see the module docstring for why each one would break the destination.",
           "", "set client_min_messages = warning;", ""]

    exts = q(cur, "select extname from pg_extension order by 1")
    out.append("-- extensions present on the SOURCE (create by hand if the destination needs one):")
    out += ["--   %s" % e[0] for e in exts] + [""]

    tables = [r[0] for r in q(cur, """
        select c.relname from pg_class c join pg_namespace n on n.oid = c.relnamespace
        where n.nspname = %s and c.relkind = 'r' order by c.relname""", (S,))]
    print("tables: %d" % len(tables))

    for t in tables:
        cols = q(cur, """
            select a.attname,
                   format_type(a.atttypid, a.atttypmod),
                   a.attnotnull,
                   pg_get_expr(d.adbin, d.adrelid),
                   a.attidentity
            from pg_attribute a
            left join pg_attrdef d on d.adrelid = a.attrelid and d.adnum = a.attnum
            where a.attrelid = %s::regclass and a.attnum > 0 and not a.attisdropped
            order by a.attnum""", ('"%s"."%s"' % (S, t),))
        lines = []
        for name, typ, notnull, default, identity in cols:
            piece = '  "%s" %s' % (name, typ)
            if identity:
                piece += " generated %s as identity" % (
                    "always" if identity == "a" else "by default")
            elif default is not None:
                piece += " default %s" % default
            if notnull:
                piece += " not null"
            lines.append(piece)
        # Table-level constraints EXCEPT foreign keys: FKs go in a later pass so the load does
        # not depend on table order, which is exactly the failure SUPABASE_RUN_ALL.sql warns
        # about (its FK section must run after the orphan cleanup for the same reason).
        cons = q(cur, """
            select conname, pg_get_constraintdef(oid), contype
            from pg_constraint where conrelid = %s::regclass and contype <> 'f'
            order by contype desc, conname""", ('"%s"."%s"' % (S, t),))
        for name, definition, _ in cons:
            lines.append('  constraint "%s" %s' % (name, definition))
        out.append('create table if not exists "%s"."%s" (\n%s\n);' % (S, t, ",\n".join(lines)))
        out.append("")

    out.append("-- foreign keys, after every table exists")
    for t in tables:
        for name, definition in q(cur, """
                select conname, pg_get_constraintdef(oid) from pg_constraint
                where conrelid = %s::regclass and contype = 'f' order by conname""",
                                  ('"%s"."%s"' % (S, t),)):
            # `if not exists` has no ADD CONSTRAINT form, so guard it the way the repo's own
            # migrations do: a catalog lookup, so re-running the file is safe.
            out.append("do $$ begin if not exists (select 1 from pg_constraint where conname = "
                       "'%s') then alter table \"%s\".\"%s\" add constraint \"%s\" %s; "
                       "end if; end $$;" % (name, S, t, name, definition))
    out.append("")

    out.append("-- indexes (primary keys and uniques already came through as constraints)")
    idx = q(cur, """
        select indexdef from pg_indexes i
        where schemaname = %s
          and not exists (select 1 from pg_constraint c where c.conname = i.indexname)
        order by tablename, indexname""", (S,))
    out += [d[0].replace("CREATE INDEX", "CREATE INDEX IF NOT EXISTS", 1)
            .replace("CREATE UNIQUE INDEX", "CREATE UNIQUE INDEX IF NOT EXISTS", 1) + ";"
            for (d,) in idx]
    out.append("")

    funcs = q(cur, """
        select pg_get_functiondef(p.oid) from pg_proc p
        join pg_namespace n on n.oid = p.pronamespace
        where n.nspname = %s and p.prokind in ('f','p') order by p.proname""", (S,))
    out.append("-- functions (db_stats/ev_usage back the admin panels; trigger functions below)")
    # NOT f[0]: the row is already unpacked by `for (f,)`, so indexing it takes the first
    # CHARACTER of the definition. That produced a file of five lines reading "C;" -- the right
    # number of entries, plausible at a glance, and it would have created triggers pointing at
    # functions that were never defined.
    out += [f.rstrip().rstrip(";") + ";" for (f,) in funcs] + [""]

    out.append("-- triggers, last: they reference the functions above")
    for t in tables:
        for (d,) in q(cur, """
                select pg_get_triggerdef(oid) from pg_trigger
                where tgrelid = %s::regclass and not tgisinternal order by tgname""",
                      ('"%s"."%s"' % (S, t),)):
            out.append(d + ";")

    conn.close()
    body = "\n".join(out) + "\n"
    with open(a.out, "w", encoding="utf-8") as fh:
        fh.write(body)
    print("wrote %s (%.1f KB)" % (a.out, len(body) / 1024.0))
    print("  %d tables, %d indexes, %d functions, %d extensions noted"
          % (len(tables), len(idx), len(funcs), len(exts)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
