"""
report_role_discovery.py — the per-ROLE breakdown of a discover_companies.py sweep.

Stage 1 (`scripts/discover_companies.py`) writes one row per employer with a `harvest_phrases`
cell recording which queries surfaced it. This turns that into the question actually being
asked: which role phrases bought us employers we do not already scrape, and of those, how many
have a board we can read?

Reuses `discover_companies.phrase_stats` rather than recomputing, so the markdown and the run's
own stdout cannot drift apart.

    python scripts/report_role_discovery.py --csv discovered_roles_2026-08-30.csv
    python scripts/report_role_discovery.py --csv d.csv --probe-csv d_probe.csv --out r.md

WRITES NOTHING but its own markdown. Read-only over the two CSVs.
"""
import argparse
import csv
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import discover_companies as dc
import scraper


def _read(path):
    if not os.path.exists(path):
        raise SystemExit("no such file: %s" % path)
    with open(path, encoding="utf-8-sig", newline="") as f:
        return list(csv.DictReader(f))


def _int(v):
    try:
        return int(v or 0)
    except (TypeError, ValueError):
        return 0


def _yes(r, col):
    return (r.get(col) or "").strip().lower() == "yes"


def probe_index(probe_rows):
    """{strict_norm_name: probe_row}.

    Keyed on _strict_norm_name -- the SAME key probe_discovered.load_candidates deduped on, so
    the join back onto the discover CSV is exact rather than fuzzy. The aggressive _norm_name
    would collapse distinct employers and credit one company's board to another.
    """
    out = {}
    for r in probe_rows:
        key = scraper._strict_norm_name(r.get("employer") or "")
        if key:
            out.setdefault(key, r)
    return out


def write_report(rows, path, src, probe=None, note=""):
    probe = probe or {}
    new = [r for r in rows if not _yes(r, "in_sources")]
    stats = dc.phrase_stats(rows)
    channels = sorted({c for r in rows for c in (r.get("channel") or "").split(",") if c})

    def boards_for(subset):
        n = 0
        for r in subset:
            p = probe.get(scraper._strict_norm_name(r.get("company") or ""))
            if p and (p.get("board_url") or "").strip():
                n += 1
        return n

    L = []
    A = L.append
    A("# Role-wide company discovery — what each role surfaced\n")
    A("Generated by `scripts/report_role_discovery.py` from `%s`.\n" % os.path.basename(src))
    if note:
        A("Run: %s\n" % note)
    A("Channels: %s. Phrases with at least one hit: %d.\n"
      % (", ".join(channels) or "(none)", len(stats)))

    A("\n## The funnel\n")
    A("- Query hits harvested (not distinct postings): **%d**"
      % sum(_int(r.get("postings_seen")) for r in rows))
    A("- Distinct employers: **%d**" % len(rows))
    A("- Already a source: %d  (of which board-table-only: %d)"
      % (len(rows) - len(new), sum(1 for r in rows if _yes(r, "in_sources")
                                   and _yes(r, "in_boards_table"))))
    A("- **NET-NEW employers: %d**" % len(new))
    A("  - with H-1B filings: %d" % sum(1 for r in new if _int(r.get("h1b_filings"))))
    A("  - with the `stem_opt` tag: %d" % sum(1 for r in new if _yes(r, "stem_opt")))
    A("  - cap-exempt: %d" % sum(1 for r in new if _yes(r, "cap_exempt")))
    A("  - body-shop shaped: %d" % sum(1 for r in new if _yes(r, "bodyshop")))
    A("  - no federal record at all: %d — rank these low, do **not** drop them; absence is not "
      "evidence of non-sponsorship"
      % sum(1 for r in new if not _int(r.get("h1b_filings")) and not _yes(r, "stem_opt")))
    if probe:
        found = boards_for(new)
        A("- Probed for a board: %d → **board found: %d** (%.1f%%)"
          % (len(probe), found, 100.0 * found / len(probe)))
        A("  - the E-Verify+ mining baseline for this same step was 3.2% (sponsors) / 1.0% (rest)")

    A("\n## What each role bought\n")
    head = "| Phrase | Hits | Employers | Net-new | **Only** | H-1B | stem_opt | cap-exempt |"
    rule = "|---|---:|---:|---:|---:|---:|---:|---:|"
    if probe:
        head += " Boards |"
        rule += "---:|"
    A(head)
    A(rule)
    solo_of = {}
    for r in new:
        parsed = dc.parse_phrases(r.get("harvest_phrases"))
        if len(parsed) == 1:
            solo_of.setdefault(next(iter(parsed)), []).append(r)
    for d in stats:
        line = ("| %s | %d | %d | %d | **%d** | %d | %d | %d |"
                % (d["phrase"], d["postings"], d["employers"], d["net_new"], d["only"],
                   d["h1b"], d["stem_opt"], d["cap_exempt"]))
        if probe:
            line += " %d |" % boards_for(solo_of.get(d["phrase"], []))
        A(line)

    A("\n**`net-new` does not sum.** An employer surfaced by five phrases is net-new for all "
      "five, so that column totals to more than the run's net-new count. `only` does sum: it is "
      "the set of net-new employers that exactly one phrase found, and it is that phrase's "
      "marginal contribution. A phrase with 300 net-new and 0 `only` bought nothing the other "
      "phrases did not already bring in. The `Boards` column, when present, counts boards found "
      "among that phrase's `only` employers, for the same reason.\n")

    A("\n## Which phrases paid, and which did not\n")
    paid = [d for d in stats if d["only"]]
    A("- Carried their own weight (found net-new employers no other phrase did): %d of %d"
      % (len(paid), len(stats)))
    zero = [d["phrase"] for d in stats if not d["only"]]
    if zero:
        A("- **Zero marginal contribution — candidates to drop next run:** %s"
          % ", ".join("`%s`" % p for p in zero))
    quiet = [p for p in dc.ALL_PHRASES if p not in {d["phrase"] for d in stats}]
    if quiet:
        A("- Returned NOTHING: %s. A phrase the site refused (429, datacenter IP) and a phrase "
          "nobody is hiring for look identical here — check before dropping one."
          % ", ".join("`%s`" % p for p in quiet))

    A("\n## Breadth check — employers seen under the most roles\n")
    A("If the widened net is mostly finding the same big employers under more titles, it is "
      "buying breadth rather than reach. The employers with the most distinct roles:\n")
    A("| Employer | Roles | Hits | Net-new | H-1B |")
    A("|---|---:|---:|---|---:|")
    wide = sorted(rows, key=lambda r: (-len(dc.parse_phrases(r.get("harvest_phrases"))),
                                       r.get("company") or ""))
    for r in wide[:10]:
        n = len(dc.parse_phrases(r.get("harvest_phrases")))
        if n < 2:
            break
        A("| %s | %d | %d | %s | %d |"
          % (r.get("company"), n, _int(r.get("postings_seen")),
             "no" if _yes(r, "in_sources") else "**yes**", _int(r.get("h1b_filings"))))

    with open(path, "w", encoding="utf-8", newline="") as f:
        f.write("\n".join(L) + "\n")
    return stats, new


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--csv", default=dc.REPORT, help="discover_companies.py output")
    ap.add_argument("--probe-csv", default="", help="probe_discovered.py output (optional)")
    ap.add_argument("--out", default="role_discovery.md")
    ap.add_argument("--note", default="", help="hours/results are not in the CSV; say them here")
    a = ap.parse_args()

    rows = _read(a.csv)
    probe = probe_index(_read(a.probe_csv)) if a.probe_csv else {}
    stats, new = write_report(rows, a.out, a.csv, probe, a.note)
    dc.print_phrase_breakdown(stats, asked=dc.ALL_PHRASES)
    print("\n%d employers, %d net-new, %d phrases with a hit" % (len(rows), len(new), len(stats)))
    print("wrote %s" % os.path.abspath(a.out))


if __name__ == "__main__":
    main()
