-- Generated by scripts/dump_schema.py from the live database.
-- Owners, grants, RLS policies and extensions are intentionally not included;
-- see the module docstring for why each one would break the destination.

set client_min_messages = warning;

-- extensions present on the SOURCE (create by hand if the destination needs one):
--   pg_stat_statements
--   pgcrypto
--   plpgsql
--   supabase_vault
--   uuid-ossp

-- sequences, before the tables whose defaults call nextval() on them
create sequence if not exists "public"."events_id_seq";

create table if not exists "public"."admin_audit" (
  "id" text not null,
  "at" timestamp with time zone default now(),
  "actor" text not null,
  "action" text not null,
  "target" text,
  "count" integer default 0,
  "detail" jsonb default '{}'::jsonb,
  constraint "admin_audit_pkey" PRIMARY KEY (id)
);

create table if not exists "public"."applications" (
  "id" text not null,
  "username" text not null,
  "company" text,
  "title" text,
  "url" text,
  "status" text,
  "applied_date" date,
  "source" text,
  "resume_used" text,
  "notes" text,
  "created_at" timestamp with time zone default now(),
  "resume_name" text,
  "match_score" smallint,
  constraint "applications_pkey" PRIMARY KEY (id)
);

create table if not exists "public"."blocked_companies" (
  "name_key" text not null,
  "name" text not null,
  "reason" text,
  "added_by" text,
  "created_at" timestamp with time zone default now(),
  constraint "blocked_companies_pkey" PRIMARY KEY (name_key)
);

create table if not exists "public"."boards" (
  "url" text not null,
  "ats_type" text not null,
  "company" text,
  "added_by" text,
  "created_at" timestamp with time zone default now(),
  constraint "boards_pkey" PRIMARY KEY (url)
);

create table if not exists "public"."events" (
  "id" bigint default nextval('events_id_seq'::regclass) not null,
  "ts" timestamp with time zone default now() not null,
  "username" text not null,
  "sid" text not null,
  "event" text not null,
  "job_url" text,
  "company" text,
  "source" text,
  "score" smallint,
  "props" jsonb default '{}'::jsonb not null,
  constraint "events_pkey" PRIMARY KEY (id)
);

create table if not exists "public"."events_daily" (
  "day" date not null,
  "username" text not null,
  "event" text not null,
  "dim" text default ''::text not null,
  "n" integer default 0 not null,
  constraint "events_daily_pkey" PRIMARY KEY (day, username, event, dim)
);

create table if not exists "public"."jobs" (
  "url" text not null,
  "found_date" text,
  "title" text,
  "company" text,
  "location" text,
  "sponsors_h1b" text,
  "match_score" integer,
  "status" text,
  "jd" text,
  "posted_verified" text,
  "posted_confidence" text,
  "loc_state" text,
  "loc_metro" text,
  "remote" boolean,
  "salary_min" integer,
  "salary_max" integer,
  "salary_period" text,
  "last_seen" date,
  "is_active" boolean default true,
  "miss_count" integer default 0,
  "first_seen" date default CURRENT_DATE,
  "exp_max_years" integer,
  "sponsor_jd" text,
  "sponsor_reason" text,
  "jd_terms" text,
  constraint "jobs_pkey" PRIMARY KEY (url)
);

create table if not exists "public"."learned_answers" (
  "username" text not null,
  "key" text not null,
  "label" text,
  "value" text,
  "type" text,
  "options" jsonb,
  "company" text,
  "count" integer default 1,
  "updated_at" timestamp with time zone default now(),
  constraint "learned_answers_pkey" PRIMARY KEY (username, key)
);

create table if not exists "public"."profiles" (
  "username" text not null,
  "name" text,
  "email" text,
  "phone" text,
  "location" text,
  "linkedin" text,
  "work_authorized" text,
  "needs_sponsorship" text,
  "default_resume" text,
  "notes" text,
  "updated_at" timestamp with time zone default now(),
  "first_name" text,
  "last_name" text,
  "pronouns" text,
  "address_line1" text,
  "address_line2" text,
  "city" text,
  "state" text,
  "postal_code" text,
  "country" text,
  "github" text,
  "portfolio" text,
  "website" text,
  "work_auth_status" text,
  "requires_sponsorship_now" text,
  "requires_sponsorship_future" text,
  "gender" text,
  "race_ethnicity" text,
  "hispanic_latino" text,
  "veteran_status" text,
  "disability_status" text,
  "desired_salary" text,
  "salary_currency" text,
  "available_start_date" text,
  "willing_to_relocate" text,
  "how_did_you_hear" text,
  "extra" jsonb default '{}'::jsonb,
  "application_defaults" jsonb default '{}'::jsonb,
  "program_end_date" text,
  "opt_type" text,
  "opt_start_date" text,
  "opt_end_date" text,
  "stem_eligible" text,
  "unemployment_days_used" text,
  "search_prefs" jsonb default '{}'::jsonb,
  constraint "profiles_pkey" PRIMARY KEY (username)
);

create table if not exists "public"."resumes" (
  "id" text not null,
  "username" text not null,
  "name" text,
  "content" text,
  "created_at" timestamp with time zone default now(),
  constraint "resumes_pkey" PRIMARY KEY (id)
);

create table if not exists "public"."scrape_status" (
  "id" text not null,
  "data" jsonb,
  "updated_at" timestamp with time zone,
  constraint "scrape_status_pkey" PRIMARY KEY (id)
);

create table if not exists "public"."tailored_cache" (
  "id" text not null,
  "username" text,
  "data" jsonb,
  "created_at" timestamp with time zone default now(),
  constraint "tailored_cache_pkey" PRIMARY KEY (id)
);

create table if not exists "public"."user_jobs" (
  "username" text not null,
  "url" text not null,
  "status" text,
  "updated_at" timestamp with time zone default now(),
  constraint "user_jobs_pkey" PRIMARY KEY (username, url)
);

create table if not exists "public"."users" (
  "username" text not null,
  "password_hash" text not null,
  "resume" text default ''::text,
  "created_at" timestamp with time zone default now(),
  "disabled_at" timestamp with time zone,
  "token_epoch" integer default 0 not null,
  constraint "users_pkey" PRIMARY KEY (username)
);

-- sequence ownership
alter sequence "public"."events_id_seq" owned by "public"."events"."id";

-- foreign keys, after every table exists
do $$ begin if not exists (select 1 from pg_constraint where conname = 'applications_username_fkey') then alter table "public"."applications" add constraint "applications_username_fkey" FOREIGN KEY (username) REFERENCES users(username) ON DELETE CASCADE; end if; end $$;
do $$ begin if not exists (select 1 from pg_constraint where conname = 'learned_answers_username_fkey') then alter table "public"."learned_answers" add constraint "learned_answers_username_fkey" FOREIGN KEY (username) REFERENCES users(username) ON DELETE CASCADE; end if; end $$;
do $$ begin if not exists (select 1 from pg_constraint where conname = 'profiles_username_fkey') then alter table "public"."profiles" add constraint "profiles_username_fkey" FOREIGN KEY (username) REFERENCES users(username) ON DELETE CASCADE; end if; end $$;
do $$ begin if not exists (select 1 from pg_constraint where conname = 'resumes_username_fkey') then alter table "public"."resumes" add constraint "resumes_username_fkey" FOREIGN KEY (username) REFERENCES users(username) ON DELETE CASCADE; end if; end $$;
do $$ begin if not exists (select 1 from pg_constraint where conname = 'user_jobs_username_fkey') then alter table "public"."user_jobs" add constraint "user_jobs_username_fkey" FOREIGN KEY (username) REFERENCES users(username) ON DELETE CASCADE; end if; end $$;

-- indexes (primary keys and uniques already came through as constraints)
CREATE INDEX IF NOT EXISTS admin_audit_at_idx ON public.admin_audit USING btree (at DESC);
CREATE INDEX IF NOT EXISTS applications_user_idx ON public.applications USING btree (username);
CREATE INDEX IF NOT EXISTS events_ts_idx ON public.events USING btree (ts DESC);
CREATE INDEX IF NOT EXISTS events_user_ts_idx ON public.events USING btree (username, ts DESC);
CREATE INDEX IF NOT EXISTS jobs_company_idx ON public.jobs USING btree (company);
CREATE INDEX IF NOT EXISTS jobs_is_active_idx ON public.jobs USING btree (is_active);
CREATE INDEX IF NOT EXISTS jobs_loc_state_idx ON public.jobs USING btree (loc_state);
CREATE INDEX IF NOT EXISTS learned_answers_user_idx ON public.learned_answers USING btree (username);
CREATE INDEX IF NOT EXISTS resumes_user_idx ON public.resumes USING btree (username);
CREATE INDEX IF NOT EXISTS tailored_cache_user_idx ON public.tailored_cache USING btree (username);

-- functions (db_stats/ev_usage back the admin panels; trigger functions below)
CREATE OR REPLACE FUNCTION public.db_stats()
 RETURNS json
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_catalog'
AS $function$
  select json_build_object(
    'db_bytes',    pg_database_size(current_database()),
    'db_pretty',   pg_size_pretty(pg_database_size(current_database())),
    'measured_at', now(),
    'tables', (
      -- NOTE the ordering lives INSIDE json_agg. Sorting the rendered JSON instead would
      -- compare total_bytes as text and put 9 MB above 400 MB.
      select coalesce(json_agg(json_build_object(
               'table',       x.relname,
               'est_rows',    x.reltuples::bigint,
               'total_bytes', x.total_bytes,
               'table_bytes', x.table_bytes,
               'index_bytes', x.index_bytes,
               'toast_bytes', x.toast_bytes,
               'pretty',      pg_size_pretty(x.total_bytes)
             ) order by x.total_bytes desc), '[]'::json)
      from (
        select c.relname, c.reltuples,
               pg_total_relation_size(c.oid)                        as total_bytes,
               pg_table_size(c.oid)                                 as table_bytes,
               pg_indexes_size(c.oid)                               as index_bytes,
               coalesce(pg_total_relation_size(c.reltoastrelid), 0) as toast_bytes
        from pg_class c
        join pg_namespace n on n.oid = c.relnamespace
        where n.nspname = 'public' and c.relkind = 'r'
      ) x)
  );
$function$;
CREATE OR REPLACE FUNCTION public.ev_usage(days integer DEFAULT 7)
 RETURNS jsonb
 LANGUAGE sql
 STABLE
AS $function$
  with w as (
    select * from public.events where ts > now() - (days || ' days')::interval
  )
  select jsonb_build_object(
    'events',   (select count(*) from w),
    'sessions', (select count(distinct sid) from w),
    'users',    (select count(distinct username) from w),
    'by_event', (select coalesce(jsonb_object_agg(event, n), '{}'::jsonb)
                 from (select event, count(*) n from w group by 1) x),
    'by_route', (select coalesce(jsonb_agg(jsonb_build_object('ep', ep, 'n', n) order by n desc), '[]'::jsonb)
                 from (select props->>'ep' ep, count(*) n from w
                       where event = 'page_view' and props ? 'ep' group by 1) x),
    -- The funnel. `shown` sums the card count each feed render reported, which is
    -- the only impression denominator that exists — per-job impressions would be
    -- ~60 rows a render and are deliberately not stored.
    'funnel',   (select jsonb_build_object(
                   'shown',   coalesce(sum((props->>'n')::int) filter (where event = 'feed_view'), 0),
                   'opens',   count(*) filter (where event = 'job_open'),
                   'likes',   count(*) filter (where event = 'action' and props->>'to' = 'liked'),
                   'applies', count(*) filter (where event = 'action' and props->>'to' = 'applied'),
                   'hides',   count(*) filter (where event = 'action' and props->>'to' = 'hidden'))
                 from w),
    -- Score-band calibration: opens and applies per 20-point band. If this curve is
    -- flat, the match score is noise and the min-score slider is a placebo.
    'by_score', (select coalesce(jsonb_agg(jsonb_build_object('band', b, 'opens', o, 'applies', a) order by b), '[]'::jsonb)
                 from (select (least(score, 100) / 20) b,
                              count(*) filter (where event = 'job_open') o,
                              count(*) filter (where event = 'action' and props->>'to' = 'applied') a
                       from w where score is not null group by 1) s),
    'top_co',   (select coalesce(jsonb_agg(jsonb_build_object('co', company, 'n', n) order by n desc), '[]'::jsonb)
                 from (select company, count(*) n from w
                       where event = 'action' and props->>'to' in ('liked', 'applied')
                         and company is not null and company <> ''
                       group by 1 order by 2 desc limit 15) c),
    -- Which of the 12 saved filters anyone actually touches. props.f holds only the
    -- keys that differ from core.DEFAULT_PREFS, so this counts real usage.
    'filters',  (select coalesce(jsonb_object_agg(k, n), '{}'::jsonb)
                 from (select k, count(*) n from w, lateral jsonb_object_keys(coalesce(props->'f', '{}'::jsonb)) k
                       where event = 'feed_view' group by 1) f),
    -- Searches that found nothing: the best available list of what the corpus is
    -- missing. Raw text is stored ONLY in this case (see analytics.py).
    'zero_q',   (select coalesce(jsonb_agg(jsonb_build_object('q', q, 'n', n) order by n desc), '[]'::jsonb)
                 from (select props->>'q' q, count(*) n from w
                       where event = 'feed_view' and (props->>'n')::int = 0 and props ? 'q'
                       group by 1 order by 2 desc limit 20) z)
  );
$function$;
CREATE OR REPLACE FUNCTION public.jobs_first_seen_keep()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.first_seen := coalesce(old.first_seen, new.first_seen, current_date);
  return new;
end $function$;
CREATE OR REPLACE FUNCTION public.jobs_first_seen_set()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.first_seen := coalesce(new.first_seen, current_date);
  return new;
end $function$;
CREATE OR REPLACE FUNCTION public.rls_auto_enable()
 RETURNS event_trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'pg_catalog'
AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$;

-- triggers, last: they reference the functions above
CREATE TRIGGER jobs_first_seen_keep BEFORE UPDATE ON public.jobs FOR EACH ROW EXECUTE FUNCTION jobs_first_seen_keep();
CREATE TRIGGER jobs_first_seen_set BEFORE INSERT ON public.jobs FOR EACH ROW EXECUTE FUNCTION jobs_first_seen_set();
