#!/usr/bin/env python3
"""Build careers_us.md: for every sponsor in sponsors.txt, a native careers page
plus a United-States-filtered LinkedIn job search. Run: python make_careers.py"""
import urllib.parse

# Native careers pages (best-effort; the 26 ATS ones are verified). Amazon is pre-filtered to USA.
NATIVE = {
    "Samsara": "https://job-boards.greenhouse.io/samsara",
    "Stripe": "https://job-boards.greenhouse.io/stripe",
    "Verkada": "https://job-boards.greenhouse.io/verkada",
    "Brex": "https://job-boards.greenhouse.io/brex",
    "Datadog": "https://job-boards.greenhouse.io/datadog",
    "Instacart": "https://job-boards.greenhouse.io/instacart",
    "SoFi": "https://job-boards.greenhouse.io/sofi",
    "Scale AI": "https://job-boards.greenhouse.io/scaleai",
    "Airbnb": "https://job-boards.greenhouse.io/airbnb",
    "Databricks": "https://job-boards.greenhouse.io/databricks",
    "Twilio": "https://job-boards.greenhouse.io/twilio",
    "Robinhood": "https://job-boards.greenhouse.io/robinhood",
    "Toast": "https://job-boards.greenhouse.io/toast",
    "Checkr": "https://job-boards.greenhouse.io/checkr",
    "Affirm": "https://job-boards.greenhouse.io/affirm",
    "Flexport": "https://job-boards.greenhouse.io/flexport",
    "MongoDB": "https://job-boards.greenhouse.io/mongodb",
    "Okta": "https://job-boards.greenhouse.io/okta",
    "Palantir": "https://jobs.lever.co/palantir",
    "Ramp": "https://jobs.ashbyhq.com/ramp",
    "Notion": "https://jobs.ashbyhq.com/notion",
    "Vanta": "https://jobs.ashbyhq.com/vanta",
    "Replit": "https://jobs.ashbyhq.com/replit",
    "Cursor": "https://jobs.ashbyhq.com/cursor",
    "Avery Dennison": "https://jobs.smartrecruiters.com/AveryDennison",
    "Experian": "https://jobs.smartrecruiters.com/Experian",
    "Google": "https://careers.google.com/jobs/results/?location=United%20States",
    "Alphabet": "https://careers.google.com/jobs/results/?location=United%20States",
    "Amazon": "https://www.amazon.jobs/en/search?country=USA&loc_query=United+States",
    "Amazon Web Services": "https://www.amazon.jobs/en/search?base_query=AWS&country=USA&loc_query=United+States",
    "Microsoft": "https://careers.microsoft.com/v2/global/en/search",
    "Meta Platforms": "https://www.metacareers.com/jobs",
    "Apple": "https://jobs.apple.com/en-us/search?location=united-states-USA",
    "Netflix": "https://explore.jobs.netflix.net/careers",
    "Nvidia": "https://www.nvidia.com/en-us/about-nvidia/careers/",
    "Intel": "https://jobs.intel.com",
    "Oracle": "https://careers.oracle.com/jobs",
    "IBM": "https://www.ibm.com/careers/search",
    "Salesforce": "https://careers.salesforce.com/en/jobs/",
    "Adobe": "https://careers.adobe.com/us/en/search-results",
    "Cisco": "https://jobs.cisco.com/jobs/SearchJobs/",
    "Qualcomm": "https://careers.qualcomm.com/careers",
    "Uber": "https://www.uber.com/us/en/careers/list/",
    "Lyft": "https://www.lyft.com/careers",
    "LinkedIn": "https://careers.linkedin.com/jobs",
    "PayPal": "https://careers.pypl.com/home/",
    "eBay": "https://careers.ebayinc.com/us/en/job-search-results",
    "Pinterest": "https://www.pinterestcareers.com/jobs/",
    "Snap": "https://careers.snap.com/jobs",
    "Block": "https://block.xyz/careers/jobs",
    "DoorDash": "https://careers.doordash.com/",
    "Coinbase": "https://www.coinbase.com/careers/positions",
    "Dropbox": "https://jobs.dropbox.com/all-jobs",
    "Snowflake": "https://careers.snowflake.com/us/en/search-results",
    "Workday": "https://www.workday.com/en-us/company/careers.html",
    "ServiceNow": "https://careers.servicenow.com/jobs/",
    "Atlassian": "https://www.atlassian.com/company/careers/all-jobs",
    "Intuit": "https://www.intuit.com/careers/job-search/",
    "Autodesk": "https://www.autodesk.com/careers/overview",
    "Micron Technology": "https://www.micron.com/careers",
    "Advanced Micro Devices": "https://www.amd.com/en/corporate/careers.html",
    "Tesla": "https://www.tesla.com/careers/search/?country=US",
    "Walmart Global Tech": "https://careers.walmart.com/technology",
    "Comcast": "https://jobs.comcast.com/",
    "Expedia Group": "https://careers.expediagroup.com/jobs/",
    "Booking.com": "https://careers.booking.com/",
    "ByteDance": "https://jobs.bytedance.com/en/position",
    "TikTok": "https://careers.tiktok.com/position",
    "Deloitte": "https://apply.deloitte.com/en_US/careers/SearchJobs",
    "Accenture": "https://www.accenture.com/us-en/careers/jobsearch",
    "Cognizant": "https://careers.cognizant.com/global-en/jobs/",
    "Infosys": "https://career.infosys.com/jobs",
    "Tata Consultancy Services": "https://www.tcs.com/careers/us",
    "Wipro": "https://careers.wipro.com/careers-home/jobs",
    "Capgemini": "https://www.capgemini.com/us-en/careers/jobs/",
    "HCL Technologies": "https://www.hcltech.com/careers",
    "Tech Mahindra": "https://careers.techmahindra.com/",
    "EPAM Systems": "https://www.epam.com/careers/job-listings",
    "Ernst & Young": "https://careers.ey.com/ey/search/",
    "PricewaterhouseCoopers": "https://www.pwc.com/us/en/careers/search-jobs.html",
    "KPMG": "https://www.kpmguscareers.com/jobsearch/",
    "McKinsey & Company": "https://www.mckinsey.com/careers/search-jobs",
    "Boston Consulting Group": "https://careers.bcg.com/global/en/search-results",
    "Booz Allen Hamilton": "https://careers.boozallen.com/jobs",
    "Leidos": "https://careers.leidos.com/search/jobs",
    "JPMorgan Chase": "https://careers.jpmorgan.com/us/en/students/search-results",
    "Goldman Sachs": "https://www.goldmansachs.com/careers/our-firm/students/",
    "Morgan Stanley": "https://www.morganstanley.com/people/students-and-graduates",
    "Citigroup": "https://jobs.citi.com/search-jobs/United%20States/",
    "Bank of America": "https://careers.bankofamerica.com/en-us/job-search",
    "Wells Fargo": "https://www.wellsfargojobs.com/en/jobs/",
    "BlackRock": "https://careers.blackrock.com/students/",
    "Fidelity Investments": "https://jobs.fidelity.com/search-jobs/United%20States/",
    "Bloomberg": "https://careers.bloomberg.com/job/search",
    "Two Sigma": "https://careers.twosigma.com/careers/SearchJobs/",
    "Citadel": "https://www.citadel.com/careers/open-opportunities/",
    "Capital One": "https://www.capitalonecareers.com/search-jobs",
    "Visa": "https://corporate.visa.com/en/jobs/",
    "Mastercard": "https://careers.mastercard.com/us/en/search-results",
    "American Express": "https://aexp.eightfold.ai/careers",
    "Pfizer": "https://www.pfizer.com/about/careers",
    "Johnson & Johnson": "https://www.careers.jnj.com/en/jobs/",
    "Merck": "https://jobs.merck.com/us/en/search-results",
    "Eli Lilly": "https://careers.lilly.com/us/en/search-results",
    "Amgen": "https://careers.amgen.com/en/search-jobs",
    "Genentech": "https://careers.gene.com/us/en/search-results",
    "UnitedHealth Group": "https://careers.unitedhealthgroup.com/search-jobs",
    "CVS Health": "https://jobs.cvshealth.com/us/en/search-results",
    # --- Ranked DOL sponsors (native pages for the larger, stable ones) ---
    "Dell": "https://jobs.dell.com/",
    "American Airlines": "https://jobs.aa.com/",
    "Bristol-Myers Squibb": "https://careers.bms.com/careers",
    "Texas Instruments": "https://careers.ti.com/",
    "Regeneron Pharmaceuticals": "https://careers.regeneron.com/",
    "GlobalFoundries": "https://careers.gf.com/",
    "Northwell Health": "https://jobs.northwell.edu/",
    "Henry Ford Health": "https://careers.henryford.com/",
    "Blackstone": "https://www.blackstone.com/careers/",
    "MassMutual": "https://careers.massmutual.com/",
    "Edwards Lifesciences": "https://jobs.edwards.com/",
    "Guidewire": "https://careers.guidewire.com/",
    "Jones Lang LaSalle": "https://www.jll.com/en-us/careers",
    "Rockwell Automation": "https://www.rockwellautomation.com/en-us/company/about-us/careers.html",
    "Bridgewater Associates": "https://www.bridgewater.com/working-at-bridgewater",
    "S&P Global": "https://careers.spglobal.com/",
    "CME Group": "https://www.cmegroup.com/careers.html",
    "Marqeta": "https://www.marqeta.com/company/careers",
    "Tradeweb": "https://www.tradeweb.com/about-us/careers/",
    "Viasat": "https://careers.viasat.com/",
    "W.W. Grainger": "https://jobs.grainger.com/",
    "Altair": "https://careers.altair.com/",
    "Santander": "https://www.santandercareers.com/",
    "ChargePoint": "https://www.chargepoint.com/about/careers",
    "BioMarin": "https://careers.biomarin.com/",
    "Ciena": "https://www.ciena.com/about/careers",
    "Anaplan": "https://www.anaplan.com/company/careers/",
    "National Grid": "https://careers.nationalgrid.com/",
    "DigitalOcean": "https://www.digitalocean.com/careers",
    "Frontier Airlines": "https://www.flyfrontier.com/about-us/careers/",
    "Toyota Motor North America": "https://www.toyota.com/careers/",
    "Alcon": "https://www.alcon.com/careers",
    "Q2": "https://www.q2.com/careers",
    "Eightfold AI": "https://eightfold.ai/careers/",
    "Aurora Innovation": "https://aurora.tech/careers",
    "AIG": "https://www.aig.com/careers",
    "Novant Health": "https://careers.novanthealth.org/",
    "WorldQuant": "https://www.worldquant.com/career-listing/",
    "Cigna": "https://jobs.thecignagroup.com/",
    "Celonis": "https://www.celonis.com/careers/jobs/",
    "Tenneco": "https://careers.tenneco.com/",
    "Clarivate": "https://careers.clarivate.com/",
    "May Mobility": "https://maymobility.com/careers/",
    "New Relic": "https://newrelic.com/about/careers",
    "BitGo": "https://www.bitgo.com/careers/",
    "Sift Science": "https://sift.com/careers",
    "Macy's": "https://www.macysjobs.com/",
    "DirecTV": "https://www.directv.com/careers/",
    "RingCentral": "https://www.ringcentral.com/careers.html",
    "LendingClub": "https://www.lendingclub.com/company/careers",
    "Jacobs": "https://careers.jacobs.com/",
    "Slalom": "https://www.slalom.com/careers",
    "Arcadis": "https://www.arcadis.com/en-us/careers",
    "AlixPartners": "https://www.alixpartners.com/careers/",
    "RSM US": "https://rsmus.com/careers.html",
    "Teradata": "https://careers.teradata.com/",
    "Saviynt": "https://saviynt.com/careers",
    "Sumitomo Mitsui Banking Corporation": "https://www.smbcgroup.com/americas/careers",
}

# A few names need disambiguation in LinkedIn keyword search.
LI_KEYWORD = {"Visa": "Visa Inc", "Block": "Block Inc", "Snap": "Snap Inc"}


def li(name):
    kw = urllib.parse.quote(LI_KEYWORD.get(name, name))
    return "https://www.linkedin.com/jobs/search/?keywords=%s&location=United%%20States" % kw


lines = [
    "# US career-page links for H-1B sponsor companies",
    "",
    "For each sponsor: its **native careers page** + a **United-States-filtered LinkedIn job "
    "search** (the reliable way to see only US roles). Native links are best-effort. If one "
    "redirects, use the LinkedIn link or search '<company> careers'.",
    "",
]
count = 0
for raw in open("sponsors.txt", encoding="utf-8"):
    s = raw.strip()
    if s.startswith("# ---"):
        lines.append("\n## " + s.strip("# -"))
        continue
    if not s or s.startswith("#"):
        continue
    native = NATIVE.get(s)
    careers = "[Careers page](%s) &middot; " % native if native else ""
    lines.append("- **%s** &middot; %s[US jobs (LinkedIn) ↗](%s)" % (s, careers, li(s)))
    count += 1

open("careers_us.md", "w", encoding="utf-8").write("\n".join(lines) + "\n")
print("Wrote careers_us.md with", count, "companies.")
